version: '3.8'

services:
  ms3-contenido:
    build: .
    container_name: ms3-contenido-materiales
    restart: unless-stopped
    ports:
      - "8003:8003"  # ← Puerto único para este microservicio
    env_file:
      - .env
    networks:
      - microservices-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8003/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      options:
        max-size: "10m"
        max-file: "3"

networks:
  microservices-network:
    external: true  # ← Red compartida con otros microservicios